
- src: https://github.com/oatakan/ansible-role-ec2
  version: origin/master

- src: https://github.com/oatakan/ansible-role-azure
  version: origin/master

- src: https://github.com/oatakan/ansible-role-vmware
  version: origin/master

- src: https://github.com/oatakan/ansible-role-ovirt
  version: origin/master

- src: https://github.com/oatakan/ansible-role-kubevirt
  version: origin/master

- src: https://github.com/oatakan/ansible-role-openstack
  version: origin/master

- src: https://github.com/oatakan/ansible-role-os-stack
  version: origin/master

- src: https://github.com/oatakan/ansible-role-openshift-add-auth-config.git
  version: origin/master
  name: oatakan.openshift-add-auth-config