
- src: https://github.com/oatakan/ansible-role-ec2
  version: origin/master

- src: https://github.com/oatakan/ansible-role-vmware
  version: origin/master

- src: https://github.com/oatakan/ansible-role-ovirt
  version: origin/master

- src: https://github.com/oatakan/ansible-role-openstack
  version: origin/master

- src: https://github.com/oatakan/ansible-role-os-stack
  version: origin/master