---

- name: Ensure required DSC module is available
  win_psmodule:
    name: UpdateServicesDsc
    state: present

- name: WSUS cleanup
  win_dsc:
    resource_name: UpdateServicesCleanup
    Ensure: Present
    CleanupObsoleteUpdates: True
    CompressUpdates: True
    CleanupObsoleteComputers: True
    CleanupUnneededContentFiles: True
    CleanupLocalPublishedContentFiles: True
