---

- name: WSUS feature installation
  win_feature:
    name: UpdateServices
    state: present
    include_management_tools: True

- name: Ensure WSUS content dir exists
  win_file:
    path: '{{ wsus_content_dir }}'
    state: directory

- name: Change content folder for WSUS
  win_command: 'wsusutil.exe postinstall CONTENT_DIR={{ wsus_content_dir }}'
  args:
    chdir: 'C:\Program Files\Update Services\Tools\'
    creates: '{{ wsus_content_dir }}\WsusContent'

- name: Create automatic approval rule
  win_shell: |
    $WSUServer = Get-WsusServer
    if (-Not ($WSUServer.GetInstallApprovalRules() | Where {$_.Name -Eq "Default Automatic Approval Rule"})) {
        $WSUServer.CreateInstallApprovalRule("Default Automatic Approval Rule")
    }
  register: automatic_rule

- name: Enable automatic approval rule
  win_shell: |
    $WSUServer = Get-WsusServer
    $AutomaticRule = $WSUServer.GetInstallApprovalRules() | Where {$_.Name -Eq "Default Automatic Approval Rule"}
    $AutomaticRule.Enabled = $True
    $AutomaticRule.Save()
    $AutomaticRule.ApplyRule()
  when: automatic_rule.changed