---

- name: Ensure required DSC module is available
  win_psmodule:
    name: xWebAdministration
    state: present

- name: Ensure max memory is set for more stable WSUS
  win_dsc:
    resource_name: xWebAppPool
    Name: WsusPool
    Ensure: Present
    State: Stopped
    restartPrivateMemoryLimit: "{{ wsus_restart_private_memory_limit }}"

- name: Ensure WSUS app pool is started
  win_dsc:
    resource_name: xWebAppPool
    Name: WsusPool
    Ensure: Present
    State: Started